### ISSUE TITLE
demo里修改节点 或 关系配色会渲染异常

### ISSUE THREAD

**Issue by hdchieh** [molamolaxxx/KGView#1]
你好，
demo里修改节点 或 关系配色会渲染异常

**Comment by hdchieh** [comment]
我直接拿你的默认配色测试的，

[
            //粉红
            { fill: "rgb(249, 235, 249)", stroke: "rgb(162, 84, 162)", text: "rgb(162, 84, 162)" },
            //灰色
            { fill: "#ccc", stroke: "rgb(145, 138, 138)", text: "#333" },
            { fill: "rgb(112, 202, 225)", stroke: "#23b3d7", text: "rgb(93, 76, 93)" },
            { fill: "#D9C8AE", stroke: "#c0a378", text: "rgb(60, 60, 60)" },
            { fill: "rgb(178, 229, 183)", stroke: "rgb(98, 182, 105)", text: "rgb(60, 60, 60)" },
            //红
            { fill: "rgb(248, 152, 152)", stroke: "rgb(233, 115, 116)", text: "rgb(60, 60, 60)" }
        ]

**Comment by molamolaxxx** [comment]
> 我直接拿你的默认配色测试的，
> 
> [
> //粉红
> { fill: "rgb(249, 235, 249)", stroke: "rgb(162, 84, 162)", text: "rgb(162, 84, 162)" },
> //灰色
> { fill: "#ccc", stroke: "rgb(145, 138, 138)", text: "#333" },
> { fill: "rgb(112, 202, 225)", stroke: "#23b3d7", text: "rgb(93, 76, 93)" },
> { fill: "#D9C8AE", stroke: "#c0a378", text: "rgb(60, 60, 60)" },
> { fill: "rgb(178, 229, 183)", stroke: "rgb(98, 182, 105)", text: "rgb(60, 60, 60)" },
> //红
> { fill: "rgb(248, 152, 152)", stroke: "rgb(233, 115, 116)", text: "rgb(60, 60, 60)" }
> ]

demo中json字段需要加上双引号""，并且把注释删去

**Comment by hdchieh** [comment]
> > 我直接拿你的默认配色测试的，
> > [
> > //粉红
> > { fill: "rgb(249, 235, 249)", stroke: "rgb(162, 84, 162)", text: "rgb(162, 84, 162)" },
> > //灰色
> > { fill: "#ccc", stroke: "rgb(145, 138, 138)", text: "#333" },
> > { fill: "rgb(112, 202, 225)", stroke: "#23b3d7", text: "rgb(93, 76, 93)" },
> > { fill: "#D9C8AE", stroke: "#c0a378", text: "rgb(60, 60, 60)" },
> > { fill: "rgb(178, 229, 183)", stroke: "rgb(98, 182, 105)", text: "rgb(60, 60, 60)" },
> > //红
> > { fill: "rgb(248, 152, 152)", stroke: "rgb(233, 115, 116)", text: "rgb(60, 60, 60)" }
> > ]
> 
> demo中json字段需要加上双引号""，并且把注释删去

谢谢 确实，好了。
